### ISSUE TITLE
NULL pointer access

### ISSUE THREAD

**Issue by Tucumanos** [DrAbcrealone/Abc-AngelScripts-For-Svencoop#2]
https://github.com/DrAbcrealone/Abc-AngelScripts-For-Svencoop/blob/c14e7ae8164baf1c4fa0de9b9ffc2119d219cd38/PaydayAmmo.as#L93

I got spammed on logs this:
Not allowed: in section 'c:/1778/svencoop_addon/scripts/plugins/PaydayAmmo.as', at (93, 7): Function MonsterCounter::timer_checkEntities:
Message: Null pointer access
ERROR: CASBaseCallable::Call: Execution of function 'MonsterCounter::timer_checkEntities' failed!
ERROR: CScheduler::Think: execution of function MonsterCounter::timer_checkEntities failed!
The plugin works fine but I got spammed thousands of times this same error ;-;

**Comment by DrAbcrealone** [comment]
Well, previous version is totally a mix of shit
so i have rewrote this plugin
If there are any new problems with the new plugin, please let me know
[you could grab it here](https://github.com/DrAbcrealone/Abc-AngelScripts-For-Svencoop/blob/PVP-real-one/PaydayAmmo.as)
